services:
  api:
    build:
      context: .
    environment:
      OMDB_API_KEY: your_key
      DB_URL: jdbc:postgresql://postgres:5432/movies_api
    ports:
      - 8082:8082
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - movie_network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - movie_network

networks:
  movie_network:
    driver: bridge