spring:
  application:
    name: movies-api
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082
csv:
  path:
    best_pictures: static/best_pictures.csv
tmp:
  valid:
    api:
      key: 42
omdb:
  apiKey: ${OMDB_API_KEY}
  url: http://www.omdbapi.com

logging:
  level:
    org:
      springframework:
        security: DEBUG